services:

  # -- Frontend -- Uncomment for use
  # frontend:
  #   build:
  #     context: ./frontend
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - API_URL=http://api:3001
  #     - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:3001}
  #   depends_on:
  #     - api

  api:
    build:
      context: ./backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - UPLOAD_DIR=/app/uploads
      - PUBLIC_API_URL=${PUBLIC_API_URL}
      - ACCESS_KEY=${ACCESS_KEY}
    volumes:
      - ./uploads:/app/uploads
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # Run prisma db push before starting the app
    command: >
      sh -c "bunx prisma db push && bun run index.ts"
